version: '3'

services:
  editoggia:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=editoggia
      - POSTGRES_PASSWORD=editoggia
    volumes:
      - .:/editoggia:z
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=editoggia
      - POSTGRES_USER=editoggia
      - POSTGRES_PASSWORD=editoggia
