"""empty message

Revision ID: 574b4c722738
Revises: 2bb254e93ad1
Create Date: 2020-05-14 19:45:31.602965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574b4c722738'
down_revision = '2bb254e93ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nb', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('fiction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fiction_id'], ['fiction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_nb'), 'chapter', ['nb'], unique=False)
    op.add_column('fiction', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('fiction', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiction', 'updated_on')
    op.drop_column('fiction', 'created_on')
    op.drop_index(op.f('ix_chapter_nb'), table_name='chapter')
    op.drop_table('chapter')
    # ### end Alembic commands ###
