"""empty message

Revision ID: 81826a75d980
Revises: 1ee0afa8a983
Create Date: 2020-05-30 18:41:01.009464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81826a75d980'
down_revision = '1ee0afa8a983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('comment', sa.Column('updated_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'updated_on')
    op.drop_column('comment', 'created_on')
    # ### end Alembic commands ###
