"""empty message

Revision ID: 8a73b29f6f05
Revises: 849e178eb99a
Create Date: 2020-05-24 17:29:15.152770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a73b29f6f05'
down_revision = '849e178eb99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('total_chapters', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'total_chapters')
    # ### end Alembic commands ###
